[global]
   server role = standalone server
   security = user
   map to guest = never
   restrict anonymous = 2
   server min protocol = SMB3_00
   server max protocol = SMB3_11
   smb ports = 445
   disable netbios = yes
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes
   unix charset = UTF-8
   dos charset = CP850
   unix extensions = no
   log file = /dev/stdout
   logging = stdout
   max log size = 0

[storage]
   path = /nas/files
   browseable = yes
   read only = no
   guest ok = no
   valid users = @NAS_USERNAME@
   create mask = 0600
   directory mask = 0700
   wide links = no
   follow symlinks = no
