const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
const dom=new JSDOM('<meta name="csrf-header" content="X-CSRF-TOKEN"><meta name="csrf-token" content="fixture"><div id="cloud" class="active"></div><dialog id="editor-dialog"><div id="editor-fields"></div></dialog>',{runScripts:'outside-only',url:'http://localhost'});
const w=dom.window,d=w.document,calls=[];let editorSubmit,uploadForm,savedContent='<script>text</script>',revision='fixture-revision',failSave=false;
w.matchMedia=()=>({matches:true,addEventListener(){}});
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
const state=[{name:'folder',path:'/folder',directory:true,size:0,modified:1},{name:'<img src=x>.txt',path:'/<img src=x>.txt',directory:false,size:10,modified:2}];
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(path,method='GET',body)=>{calls.push({path,method,body});if(path==='/cloud/trash')return [{id:'fixture-trash',path:'/deleted.txt',deletedAt:1,directory:false}];if(path==='/cloud/text'){if(failSave)throw new Error('revision conflict');assert.equal(body.revision,revision);savedContent=body.content;revision+='-next';return null;}if(path.startsWith('/cloud/preview'))return {content:savedContent,revision};if(method==='GET')return {entries:state,truncated:false,totalSpace:10000,usableSpace:9000};return null;};
w.XMLHttpRequest=class{constructor(){this.upload={};}open(){}setRequestHeader(){}send(form){uploadForm=form;this.status=201;setTimeout(()=>{this.upload.onprogress({lengthComputable:true,loaded:1,total:1});this.onload();},0);}abort(){this.onabort();}};
w.eval(fs.readFileSync('src/main/resources/static/js/live-dom.js','utf8'));
w.eval(fs.readFileSync('src/main/resources/static/js/ui.js','utf8'));
w.eval(fs.readFileSync('src/main/resources/static/js/cloud-drive.js','utf8'));
w.eval(fs.readFileSync('src/main/resources/static/js/drawers.js','utf8'));
w.WorkspaceCloud.init({api,escape,toast:()=>{},editor:(title,html,submit)=>{d.querySelector('#editor-fields').innerHTML=html;editorSubmit=submit;},confirmAction:(title,text,action)=>action()});
const tick=()=>new Promise(r=>setTimeout(r,25));const click=action=>d.querySelector('[data-cloud-action="'+action+'"]').click();
(async()=>{
 await w.WorkspaceCloud.open('cloud');assert.equal(d.querySelectorAll('#cloud img').length,0);assert.equal(d.querySelectorAll('.cloud-item').length,2);
 assert.ok(d.querySelector('.cloud-header [data-drawer-target=".cloud-sidebar"]'));
 assert.ok(d.querySelector('.cloud-header .ui-drawer-trigger svg'));
 assert.ok(d.querySelector('.cloud-create [data-cloud-action="upload"] svg'));
 assert.ok(d.querySelector('.cloud-item-open .cloud-icon svg'));
 assert.ok(d.querySelector('.cloud-item-info[aria-label] svg'));
 assert.ok(d.querySelector('[data-cloud-count]')?.closest('.cloud-view-options'));
 assert.ok(d.querySelector('.cloud-pagination').hidden,'single page keeps navigation out of the file area');
 assert.ok(d.querySelector('.cloud-view-options [data-cloud-action="reload"]'),'refresh shares the file options row');
 assert.ok(d.querySelector('.cloud-view-options [data-cloud-action="selection-toggle"]'),'selection stays with list controls');
 assert.equal(d.querySelector('#cloud').classList.contains('cloud-at-root'),true);
 assert.equal(d.querySelector('[data-cloud-location]').textContent,'내 드라이브');
 assert.equal(d.querySelector('[data-cloud-selected-count]').textContent,'0개 선택');
 click('view-toggle');assert.equal(d.querySelector('.cloud-items').dataset.layout,'grid');assert.equal(d.querySelector('[data-cloud-action="view-toggle"]').getAttribute('aria-label'),'목록 보기');
 click('view-toggle');assert.equal(d.querySelector('.cloud-items').dataset.layout,'list');
 assert.ok(d.querySelector('.cloud-action-menu').contains(d.querySelector('[data-cloud-action="delete"]')),'destructive file action stays in overflow');
 click('create-toggle');assert.ok(d.querySelector('.ui-side-drawer[data-side="bottom"][open] .cloud-create'),'mobile creation opens a bottom sheet');
 assert.equal(d.querySelector('[data-cloud-action="create-toggle"]').getAttribute('aria-expanded'),'true');
 click('folder');assert.equal(d.querySelector('.ui-side-drawer[data-side="bottom"]'),null,'choosing a create action restores the toolbar');
 assert.equal(d.querySelector('[data-cloud-action="create-toggle"]').getAttribute('aria-expanded'),'false');
 click('search-toggle');assert.ok(d.querySelector('#cloud').classList.contains('cloud-search-open'));assert.equal(d.activeElement,d.querySelector('[data-cloud-filter]'));
 click('search-toggle');click('selection-toggle');assert.ok(d.querySelector('#cloud').classList.contains('cloud-selection-open'));click('selection-toggle');
 const checkbox=d.querySelectorAll('[data-cloud-select]')[1];checkbox.checked=true;checkbox.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(d.querySelector('[data-cloud-selected-count]').textContent,'1개 선택');const actions=d.querySelector('.cloud-selection [data-cloud-normal] .cloud-action-menu');actions.open=true;assert.ok(actions.contains(d.querySelector('[data-cloud-action="copy"]')));click('copy');assert.equal(actions.open,false);await tick();const destinationForm=new w.FormData();destinationForm.set('targetName','copy.txt');await editorSubmit(destinationForm);await tick();assert.ok(calls.some(item=>item.path==='/cloud/transfers'&&item.body.copy&&item.body.source==='/<img src=x>.txt'));
 const copySource=d.querySelectorAll('[data-cloud-select]')[1];copySource.checked=true;copySource.dispatchEvent(new w.Event('change',{bubbles:true}));click('clipboard');click('home');await tick();assert.ok(d.querySelector('#cloud').classList.contains('cloud-has-paste'));assert.equal(d.querySelector('[data-cloud-paste]').disabled,false);
 const modalBefore=d.querySelector('#editor-fields').innerHTML;
 d.querySelectorAll('[data-cloud-open]')[1].click();await tick();assert.equal(d.querySelector('.cloud-editor textarea').value,'<script>text</script>');assert.equal(d.querySelectorAll('.cloud-editor script,.cloud-editor img').length,0);assert.equal(d.querySelector('#editor-fields').innerHTML,modalBefore);assert.ok(d.querySelector('#cloud').classList.contains('cloud-editing'));
 const editorInput=d.querySelector('.cloud-editor textarea'),save=d.querySelector('[data-file-save]');
 editorInput.value='changed';editorInput.dispatchEvent(new w.Event('input'));save.click();await tick();assert.equal(savedContent,'changed');assert.ok(save.disabled);
 editorInput.value='changed twice';editorInput.dispatchEvent(new w.Event('input'));save.click();await tick();assert.equal(savedContent,'changed twice');assert.ok(calls.some(item=>item.path==='/cloud/text'&&item.body.revision==='fixture-revision-next'));
 editorInput.value='unsaved';editorInput.dispatchEvent(new w.Event('input'));failSave=true;save.click();await tick();assert.equal(editorInput.value,'unsaved');assert.match(d.querySelector('[data-file-status]').textContent,/revision conflict/);assert.equal(save.disabled,false);
 await w.WorkspaceCloud.refresh();assert.equal(d.querySelector('.cloud-editor textarea'),editorInput);
 const unload=new w.Event('beforeunload',{cancelable:true});w.dispatchEvent(unload);assert.ok(unload.defaultPrevented);
 w.confirm=()=>false;d.querySelector('[data-file-back]').click();await tick();assert.ok(d.querySelector('.cloud-editor'));
 w.confirm=()=>true;d.querySelector('[data-file-back]').click();await tick();assert.equal(d.querySelector('.cloud-editor'),null);assert.equal(d.querySelector('#cloud').classList.contains('cloud-editing'),false);
 state.push({name:'image.png',path:'/image.png',directory:false,size:10,modified:2});await w.WorkspaceCloud.open('cloud');
 let released=null;w.URL.createObjectURL=()=> 'blob:fixture';w.URL.revokeObjectURL=url=>{released=url;};w.fetch=async()=>({ok:true,blob:async()=>new w.Blob(['image'])});
 d.querySelector('[data-cloud-open="/image.png"]').click();await tick();assert.equal(d.querySelector('.cloud-editor img').getAttribute('src'),'blob:fixture');assert.ok(d.querySelector('[data-file-save]').hidden);d.querySelector('[data-file-back]').click();await tick();assert.equal(released,'blob:fixture');
 let finishImage;w.fetch=()=>new Promise(resolve=>{finishImage=resolve;});d.querySelector('[data-cloud-open="/image.png"]').click();await tick();d.querySelector('[data-file-back]').click();await tick();assert.equal(d.querySelector('.cloud-editor'),null,'image loading leaves navigation available');finishImage({ok:true,blob:async()=>new w.Blob(['late'])});await tick();assert.equal(d.querySelector('.cloud-editor'),null,'late preview cannot restore a closed editor');
 state.pop();await w.WorkspaceCloud.open('cloud');
 const file=new w.File(['fixture'],'file.txt',{type:'text/plain'});Object.defineProperty(file,'webkitRelativePath',{value:'folder/file.txt'});const input=d.querySelector('[data-cloud-folders]');Object.defineProperty(input,'files',{value:[file],configurable:true});input.dispatchEvent(new w.Event('change'));await tick();await tick();assert.equal(uploadForm.get('path'),'/folder/file.txt');assert.equal(uploadForm.get('overwrite'),'false');assert.match(d.querySelector('[data-cloud-status]').textContent,/1개 업로드 완료/);
 click('trash');await tick();assert.equal(d.querySelector('[data-cloud-normal]').hidden,true);assert.ok(d.querySelector('[data-cloud-trash-only] .cloud-action-menu').contains(d.querySelector('[data-cloud-action="purge"]')));click('all');click('restore');await tick();assert.ok(calls.some(item=>item.path==='/cloud/trash/fixture-trash/restoration'&&item.method==='POST'));
 click('home');await tick();d.querySelector('[data-cloud-filter]').value='needle';d.querySelector('[data-cloud-search]').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.ok(calls.some(item=>item.path.includes('query=needle')));assert.ok(d.querySelector('#cloud').classList.contains('cloud-search-filtered'));
 for(let i=0;i<101;i++)state.push({name:'item'+i,path:'/item'+i,directory:false,size:i,modified:1});await w.WorkspaceCloud.open('cloud');assert.equal(d.querySelectorAll('.cloud-item').length,100);click('next');await tick();assert.equal(d.querySelectorAll('.cloud-item').length,3);
 console.log('PASS cloud UI: mobile create sheet, safe filenames, folder destination, copy, dedicated editor, repeated revision save, failed save buffer, discard guard, image cleanup, late response, folder upload/progress, trash restore, search');w.dispatchEvent(new w.Event('pagehide'));dom.window.close();
})().catch(error=>{console.error(error);w.dispatchEvent(new w.Event('pagehide'));dom.window.close();process.exitCode=1;});
