const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
const dom=new JSDOM('<body data-account="fixture"><div id="communications"></div><div id="editor-fields"></div></body>',{runScripts:'outside-only',url:'http://localhost',pretendToBeVisual:true});
const w=dom.window,d=w.document,calls=[];let editor,action;
w.eval(fs.readFileSync('src/main/resources/static/js/ui.js','utf8'));
w.eval(fs.readFileSync('src/main/resources/static/js/live-dom.js','utf8'));
w.eval(fs.readFileSync('src/main/resources/static/js/communications.js','utf8'));
const account={id:'account1',provider:'SLACK',label:'Fixture',capabilities:['READ','SEND','REPLY','PARTICIPANTS']};
const message={accountId:'account1',provider:'SLACK',id:'m1',conversationId:'c1',sender:'Sender',text:'<img src=x onerror=alert(1)> untrusted',timestamp:1700000000000,threadId:'',unread:null,attachments:[]};
const api=async(path,method='GET',body)=>{calls.push({path,method,body});if(path==='/communications/accounts')return [account];if(path==='/communications/providers')return [];if(path==='/communications/actions')return action?[action]:[];if(path.endsWith('/conversations'))return {items:[{accountId:'account1',provider:'SLACK',id:'c1',title:'Channel',kind:'DM',preview:'hello'}],nextCursor:''};if(path.includes('/participants?'))return path.includes('cursor=next')?{items:[{id:'U1',label:'U1'},{id:'U2',label:'<img src=x>'}],nextCursor:''}:{items:[{id:'U1',label:'U1'}],nextCursor:'next'};if(path.includes('/thread-messages?'))return path.includes('cursor=next')?{items:[message,{...message,id:'m2',text:'next reply'}],nextCursor:''}:{items:[message],nextCursor:'next'};if(path.includes('/messages?'))return {items:[message],nextCursor:''};if(path.endsWith('/actions')){action={id:'pending1',accountId:'account1',provider:'SLACK',accountLabel:'Fixture',state:'PENDING',expiresAt:Date.now()+600000,message:body};return action;}if(path.endsWith('/confirmation')){action={...action,state:'SENT'};return action;}throw new Error(path);};
w.WorkspaceCommunications.init({api,escape:w.WorkspaceUI.escape,toast:message=>{throw Error(message);},editor:(...args)=>{editor=args;d.querySelector('#editor-fields').innerHTML=args[1];},fields:{},confirmAction(){}});
const tick=()=>new Promise(resolve=>setTimeout(resolve,20));
(async()=>{
 await w.WorkspaceCommunications.open('communications');
 d.querySelector('[data-comm=conversation]').click();await tick();
 assert.equal(d.querySelector('.comm-details').hidden,true);
 d.querySelector('.comm-pane [data-comm=details]').click();await tick();assert.equal(d.querySelector('.comm-details').hidden,false);
 d.querySelector('[data-comm=details-close]').click();await tick();assert.equal(d.querySelector('.comm-details').hidden,true);
 assert.match(d.querySelector('.comm-message p').textContent,/<img/);assert.equal(d.querySelector('.comm-message img'),null);
 let textarea=d.querySelector('textarea');textarea.value='a preserved draft';textarea.dispatchEvent(new w.Event('input',{bubbles:true}));textarea.focus();textarea.setSelectionRange(3,3);
 await w.WorkspaceCommunications.open('communications');assert.equal(d.querySelector('textarea').value,'a preserved draft');assert.equal(d.activeElement,textarea);assert.equal(textarea.selectionStart,3);
 d.querySelector('[data-comm=thread]').click();await tick();assert.ok(d.querySelector('[data-comm-thread-more]'));assert.equal(d.querySelector('[data-comm-thread-content] img'),null);
 d.querySelector('[data-comm-thread-more]').click();await tick();assert.equal(d.querySelectorAll('[data-comm-thread-content] article').length,2);assert.equal(d.querySelector('[data-comm-thread-more]'),null);assert.equal(d.querySelector('textarea').value,'a preserved draft');
 d.querySelector('[data-comm=participants]').click();await tick();d.querySelector('[data-comm-participants-more]').click();await tick();assert.equal(d.querySelectorAll('[data-comm-participant-list] li').length,2);assert.equal(d.querySelector('[data-comm-participant-list] img'),null);assert.equal(d.querySelector('[data-comm-participants-more]'),null);
 const form=d.querySelector('[data-compose]');form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();
 assert.equal(action.state,'PENDING');assert.equal(calls.filter(call=>call.path.endsWith('/confirmation')).length,0);assert.match(editor[0],/전송/);
 assert.equal(JSON.parse(w.sessionStorage.getItem('workspace-communications-v1:fixture')).panes[0].id,'c1');
 assert.ok(!w.sessionStorage.getItem('workspace-communications-v1:fixture').includes('preserved'));
 await editor[2]();assert.equal(d.querySelector('textarea').value,'');assert.equal(calls.filter(call=>call.path.endsWith('/confirmation')).length,1);
 d.querySelector('[data-comm=close]').click();assert.equal(d.querySelector('.comm-pane'),null);
 console.log('Communications DOM: account/conversation, XSS text, draft/focus, approval boundary and tab metadata passed.');dom.window.close();
})().catch(error=>{console.error(error);dom.window.close();process.exitCode=1;});
