const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const dom=new JSDOM('<section class="view"><button data-notes-action="sidebar">Menu</button><aside class="notes-sidebar"><input value="draft"></aside></section><section class="view"><button data-pane="inspector">Git</button><aside class="studio-inspector"></aside></section>',{runScripts:'outside-only'});
const w=dom.window,d=w.document;let mobile=true,resize;
w.matchMedia=()=>({get matches(){return mobile},addEventListener(event,fn){resize=fn}});
w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};
w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new w.Event('close'))};
w.eval(fs.readFileSync(path.resolve(__dirname,'../../src/main/resources/static/js/drawers.js'),'utf8'));
d.dispatchEvent(new w.Event('DOMContentLoaded'));
const trigger=d.querySelector('button'),panel=d.querySelector('.notes-sidebar'),owner=panel.parentNode,input=panel.querySelector('input');
input.value='unsaved text';let delegated=0;owner.addEventListener('input',()=>delegated++);
trigger.click();let dialog=d.querySelector('dialog');
assert.ok(dialog.open);assert.equal(dialog.parentNode,owner);assert.equal(panel.parentNode,dialog);assert.equal(trigger.getAttribute('aria-expanded'),'true');assert.equal(d.body.style.overflow,'hidden');
input.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(delegated,1);
dialog.close();assert.equal(panel.parentNode,owner);assert.equal(input.value,'unsaved text');assert.equal(d.activeElement,trigger);assert.equal(d.body.style.overflow,'');
trigger.click();resize();assert.equal(d.querySelector('dialog'),null);
d.querySelector('[data-pane]').click();dialog=d.querySelector('dialog');assert.equal(dialog.dataset.side,'right');w.WorkspaceDrawers.close();
mobile=false;trigger.click();assert.equal(d.querySelector('dialog'),null);
w.dispatchEvent(new w.Event('pagehide'));dom.window.close();
console.log('PASS drawers: mobile overlay, owning app events, draft preservation, focus/scroll restoration, resize, right panel, desktop');
