const {JSDOM}=require('jsdom');
const fs=require('node:fs'),assert=require('node:assert/strict');
const dom=new JSDOM('<main><button id="navigate">Navigate</button><input id="editor"></main><aside inert></aside><dialog id="settings" open><button id="save">Save</button></dialog>',{runScripts:'outside-only',url:'http://localhost',pretendToBeVisual:true});
const w=dom.window,d=w.document;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;};
w.eval(fs.readFileSync('src/main/resources/static/js/ui.js','utf8'));
const nextTurn=()=>new Promise(resolve=>setTimeout(resolve,5));
(async()=>{
  await nextTurn();
  const input=d.querySelector('#editor');input.focus();input.value='unsaved';
  let clicks=0,keys=0,submits=0;
  d.addEventListener('click',()=>clicks++);d.addEventListener('keydown',()=>keys++);d.addEventListener('submit',()=>submits++);
  const first=w.WorkspaceUI.beginTask('Loading first');
  const dialog=d.querySelector('#workspace-activity');
  assert.equal(dialog.open,true,'locks synchronously without a delay');
  assert.equal(dialog.getAttribute('aria-modal'),'true');
  assert.ok(d.querySelector('main').hasAttribute('inert'));
  assert.ok(d.querySelector('#settings').hasAttribute('inert'),'existing modal is blocked too');
  d.querySelector('#navigate').click();d.querySelector('#save').click();
  w.dispatchEvent(new w.KeyboardEvent('keydown',{key:'k',ctrlKey:true,bubbles:true,cancelable:true}));
  d.querySelector('#editor').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  assert.deepEqual([clicks,keys,submits],[0,0,0]);
  const cancel=new w.Event('cancel',{cancelable:true});dialog.dispatchEvent(cancel);assert.ok(cancel.defaultPrevented);
  const second=w.WorkspaceUI.beginTask('Saving second');
  second();second();await nextTurn();assert.equal(dialog.open,true);assert.equal(dialog.querySelector('strong').textContent,'Loading first');
  const late=d.createElement('section');late.innerHTML='<button>Late rendered content</button>';d.body.append(late);await nextTurn();assert.ok(late.hasAttribute('inert'));
  first();assert.equal(dialog.open,true,'keeps lock through render continuations');
  const third=w.WorkspaceUI.beginTask('Chained request');await nextTurn();assert.equal(dialog.open,true);third();await nextTurn();
  assert.equal(dialog.open,false);assert.equal(d.querySelector('main').hasAttribute('inert'),false);assert.equal(late.hasAttribute('inert'),false);assert.equal(d.querySelector('aside').hasAttribute('inert'),true);
  assert.equal(d.activeElement,input);assert.equal(input.value,'unsaved');
  d.querySelector('#navigate').click();assert.equal(clicks,1);
  const failure=w.WorkspaceUI.beginTask('Failed request');try{throw Error('network failure');}catch{}finally{failure();}await nextTurn();assert.equal(dialog.open,false);
  const removed=w.WorkspaceUI.beginTask('Render replacement');input.remove();removed();await nextTurn();assert.equal(dialog.open,false);
  assert.equal(d.querySelectorAll('#workspace-activity').length,1);
  console.log('PASS global loading: immediate input lock, dialogs, concurrency, chained requests, failure cleanup, inert/focus restoration');
  dom.window.close();
})().catch(error=>{console.error(error);dom.window.close();process.exitCode=1;});
