const {JSDOM}=require('jsdom');
const fs=require('node:fs'),assert=require('node:assert/strict');
const dom=new JSDOM('<main><button id="navigate">Navigate</button><input id="editor"></main><aside inert></aside><dialog id="settings" open><button id="save">Save</button></dialog>',{runScripts:'outside-only',url:'http://localhost',pretendToBeVisual:true});
const w=dom.window,d=w.document;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;};
w.eval(fs.readFileSync('src/main/resources/static/js/ui.js','utf8'));
const nextTurn=()=>new Promise(resolve=>setTimeout(resolve,5));
(async()=>{
  await nextTurn();
  const input=d.querySelector('#editor');input.focus();input.value='unsaved';
  let clicks=0,keys=0,submits=0;
  d.addEventListener('click',()=>clicks++);d.addEventListener('keydown',()=>keys++);d.addEventListener('submit',()=>submits++);
  const first=w.WorkspaceUI.beginTask('Loading first');
  const indicator=d.querySelector('#workspace-activity');
  assert.equal(indicator.hidden,false);
  assert.equal(indicator.tagName,'DIV');
  assert.equal(indicator.getAttribute('aria-modal'),null);
  assert.equal(d.querySelector('main').hasAttribute('inert'),false);
  assert.equal(d.querySelector('#settings').hasAttribute('inert'),false);
  assert.equal(d.activeElement,input,'loading does not capture focus');
  d.querySelector('#navigate').click();d.querySelector('#save').click();
  input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'k',ctrlKey:true,bubbles:true,cancelable:true}));
  d.querySelector('#editor').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  assert.deepEqual([clicks,keys,submits],[2,1,1]);
  for(const type of ['beforeinput','wheel','touchmove','pointerdown','drop']){
    const event=new w.Event(type,{bubbles:true,cancelable:true});input.dispatchEvent(event);assert.equal(event.defaultPrevented,false,type+' remains available');
  }
  const cancel=new w.Event('cancel',{cancelable:true});d.querySelector('#settings').dispatchEvent(cancel);assert.equal(cancel.defaultPrevented,false);
  const second=w.WorkspaceUI.beginTask('Saving second');
  second();second();await nextTurn();assert.equal(indicator.hidden,false);assert.equal(indicator.querySelector('.workspace-activity-message').textContent,'Loading first');
  const late=d.createElement('section');late.innerHTML='<button>Late rendered content</button>';d.body.append(late);await nextTurn();assert.equal(late.hasAttribute('inert'),false);
  first();assert.equal(indicator.hidden,false,'keeps activity through render continuations');
  const third=w.WorkspaceUI.beginTask('Chained request');await nextTurn();assert.equal(indicator.hidden,false);third();await nextTurn();
  assert.equal(indicator.hidden,true);assert.equal(d.querySelector('main').hasAttribute('inert'),false);assert.equal(late.hasAttribute('inert'),false);assert.equal(d.querySelector('aside').hasAttribute('inert'),true);
  assert.equal(d.activeElement,input);assert.equal(input.value,'unsaved');
  d.querySelector('#navigate').click();assert.equal(clicks,3);
  const failure=w.WorkspaceUI.beginTask('Failed request');try{throw Error('network failure');}catch{}finally{failure();}await nextTurn();assert.equal(indicator.hidden,true);
  const removed=w.WorkspaceUI.beginTask('Render replacement');input.remove();d.querySelector('#save').focus();removed();await nextTurn();assert.equal(indicator.hidden,true);assert.equal(d.activeElement,d.querySelector('#save'));
  assert.equal(d.querySelectorAll('#workspace-activity').length,1);
  console.log('PASS nonblocking loading: navigation, input, dialogs, scroll events, concurrency, failure cleanup and focus preservation');
  dom.window.close();
})().catch(error=>{console.error(error);dom.window.close();process.exitCode=1;});
